### ISSUE TITLE
Error installing Smitty

### ISSUE THREAD

**Issue by williamcaput** [tomsteele/smitty#4]
Attempting to install on Kali Linux (Debian 6). Getting an error:

root@extsec:~/smitty-master# gem install smitty
Building native extensions.  This could take a while...
ERROR:  Error installing smitty:
        ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from extconf.rb:4:in `<main>'

Gem files will remain installed in /var/lib/gems/1.9.1/gems/nokogiri-1.6.6.2 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/nokogiri-1.6.6.2/ext/nokogiri/gem_make.out

**Comment by tomsteele** [comment]
Try `apt-get install ruby1.9.1-dev`. I don't have that version of Kali. I just tested the install on Kali (Debian 7), which uses 1.9.3 and it installed without issue. Let me know if this resolves it.

**Comment by williamcaput** [comment]
Installed Ruby1.9.1-dev and it works!
Got a few more errors during 'gem install smitty', but it is working. Thanks.

Building native extensions.  This could take a while...
Fetching: mail-2.6.3.gem (100%)
Fetching: css_parser-1.3.6.gem (100%)
Fetching: htmlentities-4.3.3.gem (100%)
Fetching: premailer-1.8.4.gem (100%)
Successfully installed nokogiri-1.6.6.2
Successfully installed mail-2.6.3
Successfully installed css_parser-1.3.6
Successfully installed htmlentities-4.3.3
Successfully installed premailer-1.8.4
Successfully installed smitty-1.0.1
6 gems installed
Installing ri documentation for nokogiri-1.6.6.2...
unable to convert U+2019 from UTF-8 to US-ASCII for lib/nokogiri.rb, skipping
unable to convert "\xE5" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for CHANGELOG.ja.rdoc, skipping
unable to convert "\xC3" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for CHANGELOG.rdoc, skipping
unable to convert "\xE9" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for README.ja.rdoc, skipping
unable to convert "\xE9" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for README.rdoc, skipping
unable to convert "\xE2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for ext/nokogiri/xml_node_set.c, skipping
Installing ri documentation for mail-2.6.3...
unable to convert U+00E9 from UTF-8 to US-ASCII for lib/mail/multibyte/chars.rb, skipping
unable to convert "\xC3" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/mail/multibyte/unicode.rb, skipping
unable to convert U+00FC from UTF-8 to US-ASCII for lib/mail/core_extensions/string/multibyte.rb, skipping
unable to convert U+00E9 from UTF-8 to US-ASCII for lib/mail/configuration.rb, skipping
unable to convert U+3042 from UTF-8 to US-ASCII for lib/mail/message.rb, skipping
unable to convert U+3042 from UTF-8 to US-ASCII for lib/mail/encodings.rb, skipping
unable to convert "\xC3" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for CHANGELOG.rdoc, skipping
Installing ri documentation for css_parser-1.3.6...
Installing ri documentation for htmlentities-4.3.3...
unable to convert U+0386 from UTF-8 to US-ASCII for lib/htmlentities/mappings/expanded.rb, skipping
Installing ri documentation for premailer-1.8.4...
Installing ri documentation for smitty-1.0.1...
file 'lib' not found
Installing RDoc documentation for nokogiri-1.6.6.2...
unable to convert U+2019 from UTF-8 to US-ASCII for lib/nokogiri.rb, skipping
unable to convert "\xE5" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for CHANGELOG.ja.rdoc, skipping
unable to convert "\xC3" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for CHANGELOG.rdoc, skipping
unable to convert "\xE9" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for README.ja.rdoc, skipping
unable to convert "\xE9" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for README.rdoc, skipping
unable to convert "\xE2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for ext/nokogiri/xml_node_set.c, skipping
Installing RDoc documentation for mail-2.6.3...
unable to convert U+00E9 from UTF-8 to US-ASCII for lib/mail/multibyte/chars.rb, skipping
unable to convert "\xC3" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/mail/multibyte/unicode.rb, skipping
unable to convert U+00FC from UTF-8 to US-ASCII for lib/mail/core_extensions/string/multibyte.rb, skipping
unable to convert U+00E9 from UTF-8 to US-ASCII for lib/mail/configuration.rb, skipping
unable to convert U+3042 from UTF-8 to US-ASCII for lib/mail/message.rb, skipping
unable to convert U+3042 from UTF-8 to US-ASCII for lib/mail/encodings.rb, skipping
unable to convert "\xC3" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for CHANGELOG.rdoc, skipping
Installing RDoc documentation for css_parser-1.3.6...
Installing RDoc documentation for htmlentities-4.3.3...
unable to convert U+0386 from UTF-8 to US-ASCII for lib/htmlentities/mappings/expanded.rb, skipping
Installing RDoc documentation for premailer-1.8.4...
Installing RDoc documentation for smitty-1.0.1...
file 'lib' not found

**Comment by tomsteele** [comment]
No problem. Thanks!
